<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ZIKLOA [
<!ELEMENT ZIKLOA (MODULUA+)>
<!ELEMENT MODULUA (IZENA, LABURDURA, IRAKASLEA+, DESKRIBAPENA)>
<!ELEMENT IZENA (#PCDATA)>
<!ELEMENT LABURDURA (#PCDATA)>
<!ELEMENT IRAKASLEA (#PCDATA)>
<!ELEMENT DESKRIBAPENA (#PCDATA)>
]>

<ZIKLOA>
<MODULUA>
   <IZENA>Marka-Lengoaiak</IZENA>
   <LABURDURA>ML</LABURDURA>
   <IRAKASLEA>Aitor</IRAKASLEA>
   <DESKRIBAPENA>Marka-lengoaiak</DESKRIBAPENA>
</MODULUA>
</ZIKLOA>