<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE idazleak [
  <!ELEMENT idazleak (idazlea*)>
  <!ELEMENT idazlea ((izena|jaiotzeData)+)>
  <!ELEMENT izena (#PCDATA)>
  <!ELEMENT jaiotzeData (#PCDATA)>
]>

<idazleak>
  <idazlea>
    <izena>Mario Vargas LLosa</izena>
    <jaiotzeData>1936ko martxoaren 28ean</jaiotzeData>
  </idazlea>
  <idazlea>
    <jaiotzeData>1929ko apirilaren 1ean</jaiotzeData>
    <izena>Milan Kundera</izena>
  </idazlea>
</idazleak>